# first we define the build matrix
language: c++
os: linux
arch:
  - amd64
  - arm64

# job phases are then executed in the following order

# OPTIONAL Install apt addons (https://docs.travis-ci.com/user/installing-dependencies)
addons:
  apt:
    packages:
    - libboost-filesystem-dev
    - libopenexr-dev 
    - libjpeg-dev 
    - libtiff-dev

# OPTIONAL Install cache components (https://docs.travis-ci.com/user/caching)

# before the install phase
# before_install:

# install any dependencies required
install:
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - git checkout 4.5.0
  - mkdir build
  - cmake -H. -Bbuild
  - cmake --build build --target install -- -j $(nproc)


# before the script phase
# before_script:

# run the build script
script: 
  - mkdir build
  - cmake -H. -Bbuild
  - cmake --build build --config Release --target all -- -j $(nproc)
  - ./build/tests/data_test

# OPTIONAL before_cache (if and only if caching is effective)

# when the build succeeds (e.g. building documentation), 
# the result is in TRAVIS_TEST_RESULT environment variable
# after_success:

# when the build fails (e.g. uploading log files), 
# the result is in TRAVIS_TEST_RESULT environment variable
# after_failure: 

# OPTIONAL before_deploy (if and only if deployment is active)
# OPTIONAL deploy
# OPTIONAL after_deploy (if and only if deployment is active)

# after the script phase
# after_script:
